using RepoMind.Mcp.Configuration;
using RepoMind.Mcp.Services;
using RepoMind.Mcp.Tests.TestFixtures;
using FluentAssertions;
using Xunit;

namespace RepoMind.Mcp.Tests.Tools;

public class GeneratorToolsTests : IClassFixture<TestDatabaseFixture>
{
    private readonly QueryService _sut;

    public GeneratorToolsTests(TestDatabaseFixture fixture)
    {
        var config = new RepoMindConfiguration
        {
            RootPath = "/repos",
            DbPath = ":memory:",
        };
        _sut = new QueryService(config) { TestConnection = fixture.Connection };
    }

    [Fact]
    public void GenerateAgentsMd_ContainsOverview()
    {
        var result = _sut.GenerateAgentsMd("TestProduct");

        result.Should().Contain("TestProduct");
        result.Should().Contain("3 projects");
        result.Should().Contain("Overview");
    }

    [Fact]
    public void GenerateAgentsMd_ContainsProjects()
    {
        var result = _sut.GenerateAgentsMd();

        result.Should().Contain("acme.core");
        result.Should().Contain("acme.caching");
        result.Should().Contain("acme.web.api");
    }

    [Fact]
    public void GenerateAgentsMd_ContainsDependencies()
    {
        var result = _sut.GenerateAgentsMd();

        result.Should().Contain("Internal Dependencies");
        result.Should().Contain("Acme.Core");
    }

    [Fact]
    public void GenerateAgentsMd_ContainsConventions()
    {
        var result = _sut.GenerateAgentsMd();

        result.Should().Contain("Detected Conventions");
        result.Should().Contain("net8.0");
    }

    [Fact]
    public void GenerateAgentsMd_ContainsEndpoints()
    {
        var result = _sut.GenerateAgentsMd();

        result.Should().Contain("API Endpoints");
        result.Should().Contain("api/content");
    }

    [Fact]
    public void GenerateAgentsMd_ContainsKeyInterfaces()
    {
        var result = _sut.GenerateAgentsMd();

        result.Should().Contain("Key Interfaces");
        result.Should().Contain("ICoherentCache");
    }

    [Fact]
    public void GenerateAgentsMd_ContainsFooter()
    {
        var result = _sut.GenerateAgentsMd();

        result.Should().Contain("Generated by RepoMind");
    }
}
