using RepoMind.Mcp.Configuration;
using RepoMind.Mcp.Services;
using RepoMind.Mcp.Tests.TestFixtures;
using RepoMind.Mcp.Tools;
using FluentAssertions;
using Xunit;

namespace RepoMind.Mcp.Tests.Tools;

public class GeneratorToolsTests : IClassFixture<TestDatabaseFixture>
{
    private readonly GeneratorTools _sut;

    public GeneratorToolsTests(TestDatabaseFixture fixture)
    {
        var config = new RepoMindConfiguration
        {
            RootPath = "/repos",
            DbPath = ":memory:",
        };
        var queryService = new QueryService(config, Microsoft.Extensions.Logging.Abstractions.NullLogger<QueryService>.Instance, () => fixture.Connection);
        _sut = new GeneratorTools(queryService, Microsoft.Extensions.Logging.Abstractions.NullLogger<GeneratorTools>.Instance);
    }

    [Fact]
    public void GenerateAgentsMd_ContainsOverview()
    {
        var result = _sut.GenerateAgentsMd("TestProduct");

        result.Should().Contain("TestProduct");
        result.Should().Contain("3 projects");
        result.Should().Contain("Overview");
    }

    [Fact]
    public void GenerateAgentsMd_ContainsProjects()
    {
        var result = _sut.GenerateAgentsMd();

        result.Should().Contain("acme.core");
        result.Should().Contain("acme.caching");
        result.Should().Contain("acme.web.api");
    }

    [Fact]
    public void GenerateAgentsMd_ContainsDependencies()
    {
        var result = _sut.GenerateAgentsMd();

        result.Should().Contain("Internal Dependencies");
        result.Should().Contain("Acme.Core");
    }

    [Fact]
    public void GenerateAgentsMd_ContainsConventions()
    {
        var result = _sut.GenerateAgentsMd();

        result.Should().Contain("Detected Conventions");
        result.Should().Contain("net8.0");
    }

    [Fact]
    public void GenerateAgentsMd_ContainsEndpoints()
    {
        var result = _sut.GenerateAgentsMd();

        result.Should().Contain("API Endpoints");
        result.Should().Contain("api/content");
    }

    [Fact]
    public void GenerateAgentsMd_ContainsKeyInterfaces()
    {
        var result = _sut.GenerateAgentsMd();

        result.Should().Contain("Key Interfaces");
        result.Should().Contain("ICoherentCache");
    }

    [Fact]
    public void GenerateAgentsMd_ContainsFooter()
    {
        var result = _sut.GenerateAgentsMd();

        result.Should().Contain("Generated by RepoMind");
    }

    [Fact]
    public void GenerateAgentsMd_ContainsArchitecturePatterns()
    {
        var result = _sut.GenerateAgentsMd();

        result.Should().Contain("Architecture Patterns");
        // Fixture has IRepository implementors and I*Service implementors
        result.Should().Contain("Repository Pattern");
        result.Should().Contain("Service Layer");
    }

    [Fact]
    public void GenerateAgentsMd_ContainsKeyDependencies()
    {
        var result = _sut.GenerateAgentsMd();

        result.Should().Contain("Key Dependencies");
        result.Should().Contain("ICoherentCache");
    }

    [Fact]
    public void GenerateAgentsMd_ContainsNamingConventions()
    {
        var result = _sut.GenerateAgentsMd();

        result.Should().Contain("Naming Conventions");
        result.Should().Contain("Service");
    }

    [Fact]
    public void GenerateAgentsMd_ContainsMermaidDiagram()
    {
        var result = _sut.GenerateAgentsMd();

        result.Should().Contain("```mermaid");
        result.Should().Contain("graph LR");
    }

    [Fact]
    public void GenerateAgentsMd_ContainsProjectRoles()
    {
        var result = _sut.GenerateAgentsMd();

        result.Should().Contain("Role");
        result.Should().Contain("API");
    }

    [Fact]
    public void GenerateAgentsMd_ContainsDevelopmentFlows()
    {
        var result = _sut.GenerateAgentsMd();

        result.Should().Contain("Development Flows");
    }
}
